#!/bin/bash

# Load settings
. bin/settings.sh
load_settings
settings=(${MLBVIEWER_REMOTE_SETTINGS//:/ })

mlbviewer_path=${settings[0]}
mplayer_path=${settings[1]}

# Add mplayer path in front of the environment
if [ -n $mplayer_path ]
then
    export PATH=$mplayer_path:$PATH
fi

# Start mlbviewer
(cd $mlbviewer_path; python2.7 mlbviewer.py)

