#!/bin/bash

CWD=$(dirname $0)
MLBTV_PIPE=$CWD/mlbpipe

# Create pipe for video
if [ ! -p $MLBTV_PIPE ]
then
    mkfifo $MLBTV_PIPE
fi

# Connect feed to omxplayer
cat <&0 > $MLBTV_PIPE | omxplayer -o hdmi $MLBTV_PIPE

